-- captures에 FK가 생겼으므로 부모 행이 먼저 있어야 한다.
-- 기존 테스트들이 trail_id 1~3, stream_id 1~2를 하드코딩해서 쓰므로 그 id를 그대로 만든다.
--
-- 이 시드는 @BeforeEach가 아니라 data.sql에 있어야 한다.
-- @Sql(statements=...)이 @BeforeEach보다 먼저 실행되기 때문이다(reader 테스트가 @Sql을 쓴다).
--
-- H2의 GENERATED BY DEFAULT AS IDENTITY는 명시적 id를 받아도 시퀀스를 앞당기지 않는다.
-- RESTART를 하지 않으면 이후 자동 생성 id가 1부터 나와 시드와 PK 충돌이 난다.
--
-- ⚠️ writer와 reader의 이 파일은 내용이 바이트 단위로 동일해야 한다.
--    한쪽을 고치면 다른 쪽에 그대로 복사할 것.

INSERT INTO streams (id, name, location) VALUES
    (1, 'seed-stream-1', 'SRID=4326;LINESTRING(126.97 37.55, 126.98 37.56)'),
    (2, 'seed-stream-2', 'SRID=4326;LINESTRING(127.00 37.50, 127.01 37.51)');

INSERT INTO trails (id, stream_id, camera_number, location, status) VALUES
    (1, 1, 'SEED-CAM-1', 'SRID=4326;POINT(126.97 37.55)', 'active'),
    (2, 1, 'SEED-CAM-2', 'SRID=4326;POINT(126.98 37.56)', 'active'),
    (3, 2, 'SEED-CAM-3', 'SRID=4326;POINT(127.00 37.50)', 'active');

ALTER TABLE streams ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE trails ALTER COLUMN id RESTART WITH 1000;
