CREATE TABLE IF NOT EXISTS captures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trail_id INTEGER NOT NULL,
    stream_id INTEGER NOT NULL,
    image_path VARCHAR(500) NOT NULL,
    road_status VARCHAR(10),
    confidence DECIMAL(3,2) DEFAULT 0.0,
    created_at TIMESTAMP
);
