-- 이 파일은 운영 스키마(infra/scripts/init-db.sql)를 H2에 맞게 옮긴 것이다.
-- 제약 이름은 운영 PostgreSQL이 자동 생성하는 이름과 정확히 일치시켰다.
-- TrailCommandHandler가 그 이름으로 FK/UNIQUE 위반을 구분하기 때문이다.
-- 이름을 명시하지 않으면 H2가 CONSTRAINT_A67 같은 이름을 붙여 아무것도 검증할 수 없다.
--
-- 운영에는 있지만 여기 없는 것:
--   - PostGIS extension: H2 2.3.232가 GEOMETRY를 네이티브 지원하므로 불필요하다.
--   - update_updated_at_column() 트리거: H2에 plpgsql이 없다.
--     captures.updated_at 컬럼은 두되 자동 갱신되지 않는다.
--   - 성능 인덱스: 테스트에서 의미가 없다.
--
-- ⚠️ writer와 reader의 이 파일은 내용이 바이트 단위로 동일해야 한다.
--    한쪽을 고치면 다른 쪽에 그대로 복사할 것.

CREATE TABLE IF NOT EXISTS streams (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    location GEOMETRY(LINESTRING, 4326) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS trails (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream_id INTEGER NOT NULL,
    camera_number VARCHAR NOT NULL,
    location GEOMETRY(POINT, 4326) NOT NULL,
    direction VARCHAR(50),
    status VARCHAR(20) DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT trails_stream_id_fkey FOREIGN KEY (stream_id) REFERENCES streams(id) ON DELETE CASCADE,
    CONSTRAINT trails_stream_id_camera_number_key UNIQUE (stream_id, camera_number),
    CONSTRAINT trails_status_check CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE IF NOT EXISTS captures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trail_id INTEGER NOT NULL,
    stream_id INTEGER NOT NULL,
    image_path VARCHAR(500) NOT NULL,
    road_status VARCHAR(10),
    confidence DECIMAL(3,2) DEFAULT 0.0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT captures_trail_id_fkey FOREIGN KEY (trail_id) REFERENCES trails(id) ON DELETE CASCADE,
    CONSTRAINT captures_stream_id_fkey FOREIGN KEY (stream_id) REFERENCES streams(id) ON DELETE CASCADE,
    CONSTRAINT captures_road_status_check CHECK (road_status IN ('양호', '주의', '불량'))
);
